# Generated by Django 3.1.5 on 2021-01-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('abstract', models.TextField()),
                ('image', models.ImageField(upload_to=None)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=254)),
                ('number_of_members', models.CharField(max_length=254)),
                ('twitter_thread', models.SlugField(max_length=254)),
                ('project_email', models.EmailField(max_length=254)),
                ('project_link', models.SlugField(max_length=254)),
            ],
        ),
    ]
