# Generated by Django 3.1.5 on 2021-02-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210201_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='ilarqam_email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='picture',
            field=models.ImageField(default=2, upload_to=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='twitter_account',
            field=models.URLField(default=2),
            preserve_default=False,
        ),
    ]
