# Generated by Django 3.1.5 on 2021-02-01 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210201_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='birthdate',
        ),
        migrations.AddField(
            model_name='person',
            name='lates_projects',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.project'),
        ),
    ]
