# Generated by Django 3.1.5 on 2021-02-01 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210201_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='lates_projects',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.project'),
            preserve_default=False,
        ),
    ]
