# Generated by Django 3.1.5 on 2021-02-01 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210201_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='membership',
            field=models.CharField(default=2, max_length=100, verbose_name='(٢٠١٩-الآن)'),
            preserve_default=False,
        ),
    ]
